name: vben
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.VBEN_SECRETS }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install -g n && n v12.19.0 && node --version && yarn && yarn build:vite && yarn build:no-cache
